Alice Módulo 3
dsFMAT/students_diplomado_data_science_fmat pull request #70
Opened 2024-10-15 06:53 UTC by Alice-kr39

2024-10-22 01:48 UTC, henrrynadalH requested changes
Hola @Alice-kr39 , veo que tu pull request tiene 54 archivos, ¿podrías revisar y subir únicamente los correspondientes a las tareas?

2024-11-04 23:23 UTC, henrrynadalH reviewed
Perfecto

Ejercicios 1 .... 3/3
Ejercicios 2 .... 3/3
Ejercicios 3 .... 3/3
Ejercicios 4 .... 3/3
Ejercicios 5 .... 3/3

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/1-ejercicios_sentencias_y_operadores_basicos/ejercicio_1.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/1-ejercicios_sentencias_y_operadores_basicos/ejercicio_2.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/1-ejercicios_sentencias_y_operadores_basicos/ejercicio_3.sql
Perfecto, podrías revisar que se está filtrando bien revisando la salida de los datos

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/2-ejercicios_group_by/ejercicio_1.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/2-ejercicios_group_by/ejercicio_2.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/2-ejercicios_group_by/ejercicio_3.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/3-ejercicios_group_by_y_funciones_de_agregacion/ejercicio_1.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/3-ejercicios_group_by_y_funciones_de_agregacion/ejercicio_2.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/3-ejercicios_group_by_y_funciones_de_agregacion/ejercicio_3.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/4-ejercicios_having/ejercicio_1.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/4-ejercicios_having/ejercicio_2.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/4-ejercicios_having/ejercicio_3.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/5-ejercicios_joins/ejercicio_1.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/5-ejercicios_joins/ejercicio_2.sql
Perfect

2024-11-04 23:23 UTC, henrrynadalH commented on class_of_2024/modulo_3/alicia_carballo/5-ejercicios_joins/ejercicio_2.sql
Perfecto

2024-11-04 23:23 UTC, henrrynadalH approved these changes

2024-11-04 23:23 UTC, merged

2024-11-04 23:26 UTC, Alice-kr39 commented
gracias recibido, le mande un correo.
________________________________
De: Henrry ***@***.***>
Enviado: lunes, 4 de noviembre de 2024 05:23 p. m.
Para: dsFMAT/students_diplomado_data_science_fmat ***@***.***>
Cc: Alicia Carballo Uicab ***@***.***>; State change ***@***.***>
Asunto: Re: [dsFMAT/students_diplomado_data_science_fmat] Alice Módulo 3 (PR #70)


Merged #70<https://github.com/dsFMAT/students_diplomado_data_science_fmat/pull/70> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/dsFMAT/students_diplomado_data_science_fmat/pull/70#event-15111708388>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3IGCJEHGVC6SGCJFNIKZL3Z676YFAVCNFSM6AAAAABP6NE7G6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVGEYTCNZQHAZTQOA>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>